<p>Если не возникает    исключительной ситуации,  
         ветвь except    пропускается и вы-
полнение инструкции try завершается. Если во время
 выполнения ветви try генерируется исключение, ост
                  авшаяся часть
ветви пропускается. Далее, если тип (класс) исключ
            ения соответствует указан-
ному после ключевого слова except, выполняется вет
              вь except и выполнение
инструкции try завершается.Если исключение не соот
ветствует указанному после ключевого слова except,
                        то
оно передается внешнему блоку try или, если обрабо
            тчик не найден, исключение
считается не перехваченным, выполнение прерывается
             и выводится сообщение об
                     ошибке.
                       </p>
<div id="aaqaq">Инструкция try может иметь более о
     дной ветви except, определяя обработчики
для разных исключений. Выполняться будет (как макс
          имум) только один из них. Об-
рабатываются только исключения, сгенерированные в 
          соответствующей ветви try, но
не в других обработчиках инструкции try. После клю
          чевого слова except может быть
указано несколько типов исключений в виде кортежа:
                         
 ... except (RuntimeError, TypeError, NameError):
                  ... pass<div>
             addr1@mail.ru,asa@ya.ru
В последней ветви except тип исключения может быть
               опущен - в этом слу-
чае будут обрабатываться все исключения. Используй
          те такую запись с особой осто-
рожностью - так Вы легко можете замаскировать- реа
           льные ошибки! Перехват всех
исключений можно использовать для вывода сообщения
            об ошибке, а затем повторно
сгенерировать его (позволяя обрабатывать исключени
                е в другом месте):
import sys addr2@ru addr3@sswjw. addr4$swswq.ru ad
                 dr5@wqwsqq.info
